// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eiokcgajwzhycrxfotve.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVpb2tjZ2Fqd3poeWNyeGZvdHZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwMjMyMDQsImV4cCI6MjA2MjU5OTIwNH0.GjGa--khiJ45scvXJqhTRXWeYrEZWGIVFZByxi0Wxxw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);